### ISSUE TITLE
Can't delete files

### ISSUE THREAD

**Issue by FunctionDJ** [TheQwertiest/foo_spider_monkey_panel#163]
I'm trying to run `fb.RunContextCommandWithMetadb("Delete file(s)", handle)` but it always fails (returns `false`).
Am i doing something wrong?
I tried both with a handle list and a single handle.

**Comment by marc2k3** [comment]
Well it must be `Delete File` for a handle or handle list with a count of 1 and `Delete Files` for a handle list with multiple handles. If you really meant that, don't write `Delete file(s)` because that's obviously wrong.

Also, the return value it not based on the success of the command. It's whether the command exists. And if the dialogs/operations are asynchronous, the function will return immediately anyway. Taking it to the extreme, it could be minutes/hours before whatever action is finished.

Anyway, you might find it easier to use FileSystemObject.

**Comment by FunctionDJ** [comment]
Thanks for the advice! I just used the name that i saw in the Keyboard Shortcuts settings. Using the variations you mentioned makes a lot more sense, but i don't know where they are listed. Also really good to know about the async behaviour. I'll probably end up using FSO like you recommended.

**Comment by FunctionDJ** [comment]
I appears that `fb.RunContextCommandWithMetadb("Delete files", fb.GetSelections())` only works when more than 1 track is selected, even though the result of `GetSelections()` is always a handle list.

**Comment by regorxxx** [comment]
If you check marc answer, the menu changes to Delete file whenever the list only has 1 handle. The menu is related to the handle count, not to the object prototype used. So that's not a bug but intended behavior, since the menu is created outside SMP context. Anyway you can bypass that limitation with a bit of code:
```
const handleList = fb.GetSelections();
fb.RunContextCommandWithMetadb(handleList.Count > 1 ? "Delete files" : "Delete file", handleList)
```

**Comment by FunctionDJ** [comment]
@regorxxx that's basically what i wrote already :D
i wasn't sure that these command names are *literally* taken from the available context menu, that's good to know. for some reason i thought it was just something that grew historically or something like that. thanks!
