### ISSUE TITLE
samples

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#2]
~~I'll update my own samples for this. I see it's marked on your project page as done but that's clearly not right... they don't work at all!!~~

I've decided I'm too lazy and can't be bothered.

**Comment by TheQwertiest** [comment]
That's strange, which one did I miss (aside from Brett's script)?

**Comment by marc2k3** [comment]
Pretty much nothing worked for me...

-The images path in helpers.js doesn't point at my images folder.
-lodash has been updated to version 4 but the scripts make use of deprecated features such as passing `this` to map, foreach and others. Also some chained functions end with `.value()` which is again deprecated.
-My scripts have some callbacks defined in `panel.js` which all scripts that import it use with the exception of a few that also have them defined in the main script. Because of the way precedence worked previously, the function in the main panel overrides the ones in panel.js. The `include` function of SMP reverses this so the function in the main script is ignored and the function inside panel.js gets called. This breaks a lot of stuff so that means all callbacks must be removed from panel.js and merged in to the main file. 

I then gave up because I thought what's the point.... with the exception of thumbs which can theoretically   choke on huge folders of large images, none of my scripts are going to benefit from any of the performance/new ES features you're bringing.

**Comment by TheQwertiest** [comment]
> The images path in helpers.js doesn't point at my images folder.

Argh, yeah, I've just copy-pasted helpers.js from CaTRoX... Need to review that properly.

> lodash has been updated to version 4 but the scripts make use of deprecated features such as passing this to map, foreach and others. Also some chained functions end with .value() which is again deprecated.

Hm... With the exception of Brett's script I think I've removed all deprecated `.value()` calls (not all of them were deprecated), same with `this`, but I will recheck.

> My scripts have some callbacks defined in panel.js which all scripts that import it use with the exception of a few that also have them defined in the main script. Because of the way precedence worked previously, the function in the main panel overrides the ones in panel.js. The include function of SMP reverses this so the function in the main script is ignored and the function inside panel.js gets called.

Strange that they worked for me... Probably didn't test them enough. Still, I need to provide working samples for the component to help potential new script developers...

Anyways thanks for all the info! Will recheck them again more thoroughly!

PS: Did you try using my component or just browsed through the .js code? =)
PPS: I won't update jsplaylist-mod and js-smooth for the first release, since those are quite big and I'm not familiar with them enough to make and test changes, i.e. it'll delay the release too much, since it'll require a lot of time...

**Comment by TheQwertiest** [comment]
> I did test with the actual component. 

Cool, that means that it works at least on one other computer :D


> It wasn't until I saw you'd posted the SpiderMonkey dlls that I even attempted it - there was no way I could have built that from source.

Yeah, building SpiderMonkey is not really trivial (to say the least): the ESR60 branch actually has some bugs in building scripts that make building much harder then it should've been... Note, that I've updated build instructions to simplify the component building process.


> I honestly think it would be easier to revert the lodash version than dig through it all but it's up to you.

Naaaaah, I want my bleeding edge :D
