### ISSUE TITLE
GdiDrawText rounding issue

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#20]
y-text position

GdiDrawText seems to round down (Math.floor), whereas JSP uses round (Math.round).
Result is that text carefully positioned with GdiDrawText may not be anymore!

For comparison, gr.DrawString seems to use Math.round (SMP & JSP). So it looks like a bug with GdiDrawText?

var font = gdi.Font("segoe ui", 12, 1)
function RGB(r, g, b) {return 0xff000000 | r << 16 | g << 8 | b;}
function on_paint(gr) {
    gr.FillSolidRect(0,19,50,10, RGB(255,0,0))
    gr.GdiDrawText("T", font, RGB(0,0,0), 10, 15.9, 100, 40); // SMP draws @ y = 15; JSP draws @ y = 16; i.e. Math.floor vs round
    gr.GdiDrawText("T", font, RGB(0,0,0), 15, 16, 100, 40);
    gr.DrawString("T", font, RGB(0,0,0), 30, 15.9, 100, 40); // Both SMP & JSP draw @ y = 16; i.e. rounded
    gr.DrawString("T", font, RGB(0,0,0), 35, 16, 100, 40);
}

**Comment by TheQwertiest** [comment]
Not sure what to do about it - the float/double to integer conversion is performed by JavaScript engine and currently it works as specified by ECMAScript standard:
From standard: [source](https://www.ecma-international.org/ecma-262/5.1/#sec-9.5): 
> Let posInt be sign(number) × floor(abs(number)).

Meaning that MS JScript engine actually violates ES specification, by performing `round` instead of `floor`.

**Comment by Wil-B** [comment]
Yes I think sticking with the standard is the right thing to do. I really wanted to know if it was a fixable bug or not, since the code can be tweaked.
