### ISSUE TITLE
ThemeManager Issue

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#30]
As a test to demonstrate the issue, hover and down state don't work for me in SimpleThemedButton.txt sample.

It looks like stateid in SetPartAndStateID isn't being recognised?

**Comment by TheQwertiest** [comment]
Fixed in the [latest build](https://ci.appveyor.com/api/projects/theqwertiest/foo-spider-monkey-panel/artifacts/_result%2FWin32_Release%2Ffoo_spider_monkey_panel.fb2k-component?branch=master&job=Configuration%3A%20Release).

**Comment by Wil-B** [comment]
I thought I would confirm that the issue is fixed in the latest build.

But I am now seeing a new error:
Build: 13:58:32, Oct 18 2018. Issue:
Error: Spider Monkey Panel v1.0.3 (JS Smooth Playlist by Br3tt aka Falstaff)
'FillPolygon' failed:
Points count must be a multiple of two

File: JScommon.js
Line: 734, Column: 2

I checked the points count & it looks as though it's 6.

The 'FillPolygon' error is also effecting most of my scripts.

**Comment by TheQwertiest** [comment]
Haha, what a dumb mistake :D
Anyways, fixed in the latest build.

**Comment by Wil-B** [comment]
Thanks for FillPolygon fix. However, some stability issues have arisen for me since the 1.0.3 release.

1. Crash on shutdown + occasionally on changing DUI layout: Build: 12:11:41, Oct 19 2018 [no crash with release version of 1.0.3]
	Crash report 
[shutdown crash.zip](https://github.com/TheQwertiest/foo_spider_monkey_panel/files/2498292/shutdown.crash.zip)

	I've only checked DUI: the bigger the multi-tab DUI layout & more SMP panels the more likely it will occur.

2. Error: Spider Monkey Panel v1.0.3 (info) : Out of memory: Build: 12:11:41, Oct 19 2018 [no memory errors with release version of 1.0.3]

 During normal usage, Build: 12:11:41, Oct 19 2018 is giving 'out of memory' errors. The v1.0.3 release version doesn't give the errors.
- when it errors, fb2k is only using 200-346 mb of memory & total memory usage is 25-33%. All spider monkey panels in the layout report the error.
- error seems to occur when artist images change or switch between cover & artist image.
- this is seen in a multi-tab DUI layout which has a number of artist/cover display type SMP panels.
- perhaps it's due to this commit: "Art handling code cleanup"????

If you need to reproduce the 'Out of memory issue' in a test scenario try:
- create DUI layout with 6-8 tabs each with SMP & Yt Mgr (use your version you linked: https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/16)
- Click yT button so in image mode. Spam the images, i.e. switch tabs, single click images to toggle cover/artist and use the mouse wheel to spin through the artist images.
- For me I see an 'out of memory' error within about 30 seconds of doing this with that Yt Mgr version: usually while spinning through the artist images.
- Enable "Image [Artist] Auto-Fetch" or set Image [Artist] Folder Location in panel properties if you need artist images for display by Yt Mgr.

Sorry to be finding more apparent teething problems...

Since it's a latest build, and not a release, I haven't started a new issue.

**Comment by TheQwertiest** [comment]
> Sorry to be finding more apparent teething problems...

Haha, it's the opposite: I'm glad that someone is testing dev-builds, thus I can fix errors before publishing the actual release and avoid having to release a new bug-fix release =)

> Since it's a latest build, and not a release, I haven't started a new issue.

Please start a new issue, when it's a non trivial bug (like this one), even if it's on dev-build, since it hard to track it otherwise.

> The v1.0.3 release version doesn't give the errors.

That's because I broke `out of memory` check in v1.0.3. And by "broke" I mean that there is no OOM check at all :D

> when it errors, fb2k is only using 200-346 mb of memory

Actually it uses much more. There is a very nasty thing about some WinApi objects (e.g. GdiPlus image objects): they are allocated on kernel memory and not in the memory of the process. For example, you load a 5000x5000px 32bit depth image, it's size in memory should be 5000x5000x32/8 = 100mb, BUT (!) you won't see such an increase in fb2k RAM usage - you can see it only in `task manager` > `performance` > `kernel memory`.  
So, while you think that fb2k uses only 200-346mb of RAM it most likely uses MUCH more through kernel memory. I'm tracking both usual physical RAM usage and kernel RAM usage, so that's why you may see OOM errors, when you think that you should not.

Anyways, I've found a small error in image size calculation, which causes OOM error earlier than it should. And I'm trying to improve GC handling, which might reduce the RAM usage by collecting resources earlier.

> Crash on shutdown + occasionally on changing DUI layout: Build: 12:11:41, Oct 19 2018 [no crash with release version of 1.0.3]

Could you post reproduction steps, please?
