### ISSUE TITLE
"Apply" regression and foobar2000 freezes

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#40]
1) Thanks for the original "Apply" fix, which all seemed to work in 1.1.1.

However, there seems to have been a regression in 1.1.2-beta. At least on my machine the following don't load images when press "Apply" in configure or panel properties. They do work if press "OK".
gdi.LoadImageAsyncV2
utils.GetAlbumArtAsyncV2
(I didn't test any other async operations)
I like the extra flexibility that the V2 versions offer, & so they are an excellent addition. So I hope this can be fixed to make testing easier.

2) Deadlocks (foobar2000 not responding:  I have to exit the program).

I see you fixed some freezes. However, I still see some (1.1.1 & 1.1.2 beta). These seem to be due to a bad interaction with other applications. Specifically they occur after pasting into an existing panel property. I noticed it as I have title format snippetts in Word (Word files weren't in a foobar2000 folder). Occasionally the deadlock is immediate after OKing panel properties. More likely it eventually occurs after using the script menu to change the layout, type of image view or theme. It may require quite a number of changes before the deadlock occurs and perhaps a layout where a lot of image handling & rearranging is involved, but I'm not sure (it occurs with both old async & new V2 async methods). It doesn't matter what text is pasted in. I've seen the issue after pasting from Word, another word processor, internet explorer & gmail running in former.

Importantly, the issue doesn't occur in the absence of a paste event or if the same text is pasted from notepad or notepad++, which, along with console traces, indicates it's a not a problem with the scripts. It also doesn't occur if text is typed in.

Anyway seeing as I spotted the issue I thought I would draw your attention to it in case you can see a fix. Now I know what's going on, I can avoid the problematical scenarios, and so it's not a big problem for me. But others could encounter it...

**Comment by TheQwertiest** [comment]
Thanks for the bug report! 
I'm currently on vacation (without a proper PC), but I'll take a look once I'm back =)

**Comment by TheQwertiest** [comment]
> At least on my machine the following don't load images when press "Apply" in configure or panel properties

Regretfully, this is by design: ECMAScript requires that all jobs (which includes Promises as well) are executed only once script executing stack is empty. In other words, Promise can't be executed while the there is an active JavaScript scope. 

`Configure` dialog is a blocking operation, thus it prevents the clearing of JavaScript stack and therefore the execution of Promises.

This limitation brings some advantages as well though: your Promise will never execute while there is some other JavaScript code being executed. I.e. Promise won't ever interrupt any function in mid-execution and change variables that could result in a broken state. 

`fb.DoDragDrop`, `MenuObject.TrackPopupMenu`, `window.ShowProperties` and a few others methods also block and prevent Promises execution.

But, IMHO, potential pros of Promises greatly outweighs this con =)

**Comment by TheQwertiest** [comment]
PS: The corresponding part of ECMAScript, that describes jobs execution policy - https://www.ecma-international.org/ecma-262/6.0/#sec-jobs-and-job-queues

**Comment by TheQwertiest** [comment]
> Deadlocks

I'll take a look at the code, but most likely I will need your help in diagnosing this issue (once I'm near a proper PC), since I've never encountered it myself.

**Comment by TheQwertiest** [comment]
Regretfully, I can't reproduce the issue, so I need your help.

I need a memory dump which is captured during the freeze/deadlock. Sorry in advance for the probably unnecessary lengthy instruction, since I don't know, if you have any experience working with Visual Studio.

Preparation:
1. Download `Visual Studio 2017 Community Edition` (free at https://visualstudio.microsoft.com/en-us/downloads/).
2. Install it with `Development of Classic C++ Applications` option enabled.
3. Download and install nightly SMP build: https://ci.appveyor.com/api/projects/theqwertiest/foo-spider-monkey-panel/artifacts/_result%2FWin32_Release%2Ffoo_spider_monkey_panel.fb2k-component?branch=master&job=Configuration%3A%20Release
4. Download SMP PDB symbols archive and unpack them into SMP component folder (e.g. `foobar2000\user-components\foo_spider_monkey_panel`): https://ci.appveyor.com/api/projects/theqwertiest/foo-spider-monkey-panel/artifacts/_result%2FWin32_Release%2Ffoo_spider_monkey_panel_pdb.zip?branch=master&job=Configuration%3A%20Release

Memory dump capture (once fb2k freezes/deadlocks):
1. Open Visual Studio.
2. `Debug`>`Attach to Process...` (or press `CTRL-ALT-P`).
3. Select `foobar2000` process (make sure that `Attach to:` field is set to `Native Code` only).
4. `Debug`>`Break All` (or press `CTRL-ALT-Break`).
5. Click on `Debug`>`Save Dump As...` and save it to the location of your choice.
6. Post the resulted dump on the sharing service of your choice. Or, if you don't have one that can be used with big files, I can PM you the link to my private one.

**Comment by TheQwertiest** [comment]
In the mean time I will continue trying to find it manually by looking through the code...

**Comment by TheQwertiest** [comment]
Updated post with instructions with an easier method to capture memory dump without Visual Studio.

**Comment by TheQwertiest** [comment]
That was fast!
Sent you a msg via hydrogenaud.io PM

**Comment by Wil-B** [comment]
I've uploaded 3 dumps obtained with latest 1.1.2 beta, each from a separate deadlock. One prepared with Task Manager & two with procdump. 

HTH

**Comment by TheQwertiest** [comment]
Thanks!!! Hopefully it will be enough =)

**Comment by TheQwertiest** [comment]
Could you test the latest nightly build?
Added a dirty(?) workaround, which (in theory) should fix the deadlock.

**Comment by Wil-B** [comment]
Thanks for the test version & trying to sort the problem.

Unfortunately the issue isn't fully resolved (tested in a multi-tab DUI layout).

Freezes*** are still occurring but are now restricted to the affected SMP panel. SMP panels in other tabs and foobar2000 seem OK.

*** i.e. script menu & nothing works in affected panel + if go to another tab can't open the tab containing the affected panel.

**Comment by TheQwertiest** [comment]
Darn... Could you post memory dumps with the newest version, plz? (upload dump login/pass is still the same)

**Comment by TheQwertiest** [comment]
Do you have a sample script perhaps, that reproduces this problem?

**Comment by TheQwertiest** [comment]
Nvm, I think I've found the problem, which causes the panel freeze. Please check the latest nightly build once it's ready.

**Comment by Wil-B** [comment]
I've run the test scenario many times & I'm pleased to say that so far I haven't had any freezes.

Thanks for the fix (& also the typo issue fix).

**Comment by TheQwertiest** [comment]
That's awesome! Thanks for all the testing =)
