### ISSUE TITLE
GdiPlus error in GdiBitmap.Clone

### ISSUE THREAD

**Issue by TheQwertiest** [TheQwertiest/foo_spider_monkey_panel#57]
See https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/53#issuecomment-456453629

**Comment by TheQwertiest** [comment]
@Ottodix , could you please try the `new GdiBitmap`-copy scenario with the latest test build? It should produce a proper error message now.

**Comment by Ottodix** [comment]
Hello! So far, no error messages, because it doesn't crash anymore :)
But my cover-cache shared by all panels is now a dead feature :'(  Cloning a full array of images for all panels is too slow, and take too much memory, I've got out of memory issues now. Nothing unexpected though, and I coded another solution which is fast enough :)

There is a bug with StackBlur with this version though, it doesn't crash, but it produce a blurred image with blurred white on the left and top sides. You can try using the biography panel by WilB https://hydrogenaud.io/index.php/topic,112913.50.html#msg967659

**Comment by Ottodix** [comment]
For this StackBlur bug, it look like the blurred image is misaligned with the final image, shifted a little bit on the bottom-right

**Comment by Ottodix** [comment]
Some time ago, you said " AFAIK GdiBitmap.Clone does not actually allocate any additional memory, it will only copy image if you modify it (aka copy-on-write). I will adjust JS memory tracking to take that in account."
So i must add, about those out of mermory errors that i have now, it look like the memory usage is higher only temporary, when the array of images is beeing cloned. After, if the panel doesn't crash during the clone because of a "out of memory" error, the memory go back to the previous level, like if the newly cloned array of image didn't increase the total memory used.

**Comment by TheQwertiest** [comment]
Ok, I've finally reproduced the GdiPlus error in constructor, and now, with the improved logging we can finally see what the problem was! It. Is. ... "Failed to create GdiPlus object (0X3): OutOfMemory" -_-

It seems that despite MSDN documentation it actually allocates on every copy instead of utilizing copy-on-write...

**Comment by TheQwertiest** [comment]
Note to self: closing, since it's not something that should be fixed, it's just an OOM error.

**Comment by Ottodix** [comment]
Yep. Thanks! You tackle all those bugs one by one like a professional hitman. The issue is : with such success, people will be continuously coming to you with new targets to kill : )

**Comment by TheQwertiest** [comment]
... In the context of this bug, your praise sounds like a sarcasm ... Since I have not actually fixed anything here :D

**Comment by Ottodix** [comment]
True :) That wasn't sarcastic though, as i had a backup plan, my foobar layout doesn't depend on an eventual fix, so... Here the sentence "That's not a bug, that's a feature !" isn't cynical in a way. In a way, I do think that generally, in life, we are as much interested in finding the answers as solving the problems. (Coder's philosophic bible, LT 4,30-32 : )

**Comment by TheQwertiest** [comment]
True, it's much better when error comes from a defined behaviour, rather than from the (potentially unicorn summoning and universe annihilating) undefined behaviour :)
