### ISSUE TITLE
Strings containing NULL character are truncated

### ISSUE THREAD

**Issue by 2ji3150** [TheQwertiest/foo_spider_monkey_panel#89]
Looks like some of binary strings are not properly generate.
For example :

```
var filename = "D:\\Users\\Desktop\\bin3"; //example
var stm = new ActiveXObject('ADODB.Stream');

stm.Open();
stm.Type = 2; //adTypeText
stm.Charset = 'iso-8859-1';
stm.WriteText(String.fromCharCode(0x61)); //OK
stm.WriteText(String.fromCharCode(0x00)); //NG (ignored)
stm.WriteText(String.fromCharCode(0x62)); //OK
stm.WriteText(String.fromCharCode(0x63, 0x00, 0x64)); //NG (ignored 0x00 0x64)

stm.Position = 0;
stm.Type = 1; //adTypeBinary
stm.SaveToFile(filename, 2);
stm.Close();
 ```

Opened the output file bin3 file with a binary editor, it becomes 61 62 63 and it turns out that 0 and 0x64 were ignored.
It should be 61 00 62 63 00 64 if it works properly.
BTW, When in JScript Panel, it works properly.

**Comment by TheQwertiest** [comment]
This is a rather non-trivial problem: turns out, that JS does not consider `0x00` as a terminating character for the string, while 99% of other modern languages (including C++) do. 
This is also complicated by the fact that it's often required (internally in SMP) to convert between UTF-16 strings (used by JS engine) and UTF-8 strings (used by fb2k API).

Regardless, I'll be honest with you: while this *is* a non-conforming behaviour you are experiencing (in regards to ECMAScript standard), but such scenario (a string containing NULL character) feels rather 'edge-case'y and I doubt I'll ever fix it.

The better solution for your scenario would be either to use valid UTF-16 strings or use `ADODB.Stream.Write` method instead of `ADODB.Stream.WriteText`. 

Note: it seems that `ADODB.Stream.Write` does not currently work, so a new issue will be created and I'll be looking it later.

**Comment by TheQwertiest** [comment]
Note to self: document non-conforming behaviour on wiki.

**Comment by TheQwertiest** [comment]
This scenario is now possible to implement on nightly SMP version via `ActiveX_CreateArray` method. 

Example:
```js
let filename = "D:\\Users\\Desktop\\bin3";
let bin_data = ActiveXObject.ActiveX_CreateArray([0x63, 0x00, 0x64], 0x11) // VT_UI1

let stm = new ActiveXObject('ADODB.Stream');
stm.Open();
stm.Type = 1; // binary
stm.Write(bin_data)
stm.SaveToFile(filename, 2);
stm.Close();
```

**Comment by TheQwertiest** [comment]
Added this issue to the list of the known bugs: https://theqwertiest.github.io/foo_spider_monkey_panel/docs/script_documentation/known_bugs/
